### ISSUE TITLE
Support .NET 5.0

### ISSUE THREAD

**Issue by johnye2e** [vignetteapp/MediaPipe.NET#12]
Why is .NET 5.0 not supported?

**Comment by adryzz** [comment]
.NET 5 is not LTS and it has been replaced by .NET 6, that has almost no breaking changes. There's no point in targeting .NET 5 when .NET 6 is out.

**Comment by sr229** [comment]
Marking wontfix. We do not plan to support a runtime that is about to go out of support. We will only maintain support on LTS versions.

**Comment by johnye2e** [comment]
Thanks for your answer. Unfortunately, I can't use your code with VS 2019, because it does not support .NET 5 (I have to build your library using CLI tools with .NET 6 SDK installed).

**Comment by adryzz** [comment]
But... VS2022 is out

**Comment by Speykious** [comment]
> Marking wontfix. We do not plan to support a runtime that is about to go out of support. We will only maintain support on LTS versions.

As @adryzz points out, VS2022 is out. I recommend you update your IDE as I'm sure it will also support the older versions until their end of time.

Also, there's another reason that we want to use .NET 6: nullables and NativeMemory, since we have to use pointers all over the place to bind to the underlying native C++ MediaPipe code, and that it is better to use that than relying on a third-party unmanaged array for instance.
