### ISSUE TITLE
should face_mesh_desktop_live.pbtxt be included in the repo?

### ISSUE THREAD

**Issue by dbruning** [vignetteapp/MediaPipe.NET#14]
Trying to run the samples, and the FaceMesh sample throws error: 

Could not find a part of the path '<...>\Mediapipe.Net.Examples.FaceMesh\bin\Debug\net6.0\mediapipe\graphs\face_mesh\face_mesh_desktop_live.pbtxt'.

... maybe face_mesh_desktop_live.pbtxt and face_mesh_desktop_live_gpu.pbtxt just haven't been added to the repo yet?

**Comment by Speykious** [comment]
What you need to do is to include the `mediapipe/graphs/` and `mediapipe/modules/` folders from the original MediaPipe repository from Google.
https://github.com/google/mediapipe/tree/master/mediapipe

The reason we don't include them is because (at least for the modules) they take a huge amount of space, and it would thus massively clutter the repo which is not ideal when you want to clone it locally especially if you don't have good internet.

However, we do plan on making it so that it is possible to use the base calculators that we provide without having that folder lying around - modules and graphs would be fetched from a DLL resource using a custom resource provider. We still haven't done anything on this, but we will shortly.

**Comment by dbruning** [comment]
Understood - thankyou. 
In the meantime, I've added an itemgroup to my Mediapipe.Net.csproj which will copy from the mediapipe repo locally into the correct folder for deployment, in case it would help anyone else:

```
<ItemGroup>
<!--    Include mediapipe\graphs and mediapipe\modules directories from main mediapipe repo,-->
<!--    see: https://github.com/vignetteapp/MediaPipe.NET/issues/14-->
    <Content Include="C:\code\mediapipe\mediapipe\graphs\**\*.*">
      <Link>mediapipe\graphs\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="C:\code\mediapipe\mediapipe\modules\**\*.*">
      <Link>mediapipe\modules\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

```
