### ISSUE TITLE
Epic: libmuxr to replace current runtime

### ISSUE THREAD

**Issue by sr229** [vignetteapp/MediaPipe.NET#30]
Due to the myriad of issues we have encountered with our current wrapper, it's sufficient to say that we cannot trust the wrapper we derived from homuler due to testability, reproducibility of issues, and everything is just a black hole to us. Therefore, the next major task is re-architecting the wrapper to a new implementation.

## Introduction to MUXR: The MediaPipe Universal eXtension Runtime

libmuxr, or simply MUXR, is our answer to a lot of issues we've encountered during the creation of MediaPipe.NET and porting MediaPipeUnity as Akihabara. MUXR aims to do the following:

- MUXR should handle every pointer ownership by MediaPipe. Any implementing API on top of it should not be able to touch the MediaPipe pointers as much as possible.
- Produce a Facade approach to the API, which is, make a C-compatible and convenient library as much as possible: which opens MUXR to be integrated by other languages if we wish to which only supports C ABIs.
- Invoking MUXR should be as easy as instantiating a new MediaPipe context in the Browser.

Of course a lot of the APIs we use like custom resources should still be supported, but we will have to re-architect everything including the wrapper to accomodate this new architecture.

**Comment by sr229** [comment]
Related Literatures:

#9 
#18 
#19 
#29

**Comment by Speykious** [comment]
Basically: the problem with the current MediaPipe runtime is that we directly expose internal MediaPipe components. This is fine in C++, but not in any other language, as even Google provides a facade for them, such as Java (for Android), Objective C (for iOS) and Python.

(Javascript is different as they quite literally reimplemented their calculators in Typescript.)

We want to take the same approach and rewrite the C++ runtime so that it exposes C functions that will be at the level of MediaPipe.NET's current `Calculator`s instead of `CalculatorGraph`s, `OutputStreamPoller`s and `Packet`s.
