### ISSUE TITLE
How to extract facial landmarks in xamarin forms app

### ISSUE THREAD

**Issue by amalcty** [vignetteapp/MediaPipe.NET#35]
Can you provide sample code or documentation to extract facial landmarks from image in a xamarin forms app.

**Comment by Speykious** [comment]
An example to extract facial landmarks can be found in the [MediaPipe.Examples.FaceMesh](https://github.com/vignetteapp/MediaPipe.NET/tree/master/Mediapipe.Net.Examples.FaceMesh) project.

You don't need to extract it from any image, it's a simple structure containing 3D landmark coordinates.
If you want, you can also use [Moetion](https://github.com/vignetteapp/Moetion), our C# port of Kaleidokit, which will give you more well-defined structures such as a `Face` class, instead of a flat list.

**Comment by Speykious** [comment]
woops, sorry, didn't mean to do that

**Comment by amalcty** [comment]
Is there a way to add this in a project targeting netstandard2.1 ?

**Comment by amalcty** [comment]
Okay, thanks. Is there some kind of samples or documentation available for creating such bindings ?

**Comment by adryzz** [comment]
unfortunately not, otherwise we would have fixed the memory leak much sooner -_-

**Comment by amalcty** [comment]
Oh okay :(

**Comment by amalcty** [comment]
Oops, I don't have the expertise to pull that off.
